name: Run Node.js with Native MongoDB Service

on:
  pull_request:
    branches:
      - main

jobs:
  run_with_mongo:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0               
        ports:
          - 27017:27017                

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'   

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: sleep 15s 

      - name: Run node index.js
        env:
          MONGO_URI: mongodb://localhost:27017/test  # Local MongoDB URI
        run: |
          node index.js
